# Generated by Django 2.2.6 on 2019-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registers',
            name='area_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registers',
            name='confirm_Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registers',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registers',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registers',
            name='Gender',
            field=models.CharField(max_length=1),
        ),

    ]
