# Generated by Django 2.2.6 on 2019-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191031_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
