# Generated by Django 2.2.6 on 2019-11-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tot_qty',
            new_name='tot_qty1',
        ),
    ]
