# Generated by Django 2.2.6 on 2019-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_auto_20191112_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tot_qty',
            new_name='totqty',
        ),
    ]
