# Generated by Django 2.2.6 on 2019-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_auto_20191112_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='static/media/images'),
        ),
    ]
