# Generated by Django 2.2.6 on 2019-11-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
