# Generated by Django 2.2.6 on 2019-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('units', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tuprice', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
