# Generated by Django 2.2.6 on 2019-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20191105_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/media/images'),
        ),
    ]
