# Generated by Django 2.2.6 on 2019-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_auto_20191114_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
